export const podcasts = 
    ["http://rss.art19.com/the-daily",
    "https://www.npr.org/rss/podcast.php?id=510318", 
    "http://www.npr.org/rss/podcast.php?id=510289", 
    "https://www.npr.org/rss/podcast.php?id=510325", 
    "https://www.northcountrypublicradio.org/sotdRSS.php", 
    "http://maximumfun.org/feeds/are.xml", 
    "http://www.npr.org/rss/podcast.php?id=510298", 
    "http://feeds.feedburner.com/disparamargotdispara/podcast", 
    "https://www.npr.org/rss/podcast.php?id=510310", 
    "http://feeds.soundcloud.com/users/soundcloud:users:16745745/sounds.rss", 
    "http://lorepodcast.libsyn.com/rss", 
    "http://feeds.feedburner.com/SlatesTrumpcast", 
    "http://feeds.feedburner.com/DrNetas", 
    "http://feeds.soundcloud.com/users/soundcloud:users:206137365/sounds.rss", 
    "https://softwareengineeringdaily.com/feed/podcast/", 
    "http://www.abc.net.au/radionational/feed/2888650/podcast.xml", 
    "https://rss.art19.com/conspiracy-theories", 
    "https://www.npr.org/rss/podcast.php?id=510313", 
    "https://www.npr.org/rss/podcast.php?id=510317", 
    "https://rss.art19.com/haunted-places", 
    "http://feeds.soundcloud.com/users/soundcloud:users:38128127/sounds.rss", 
    "https://www.npr.org/rss/podcast.php?id=510282", 
    "http://feeds.feedburner.com/freakonomicsradio", 
    "https://www.heavybit.com/category/library/podcasts/jamstack-radio/feed/", 
    "https://rss.acast.com/theeconomistallaudio", 
    "http://classicalclassroom.libsyn.com/rss", 
    "http://feeds.nightvalepresents.com/sleepwithme", 
    "http://feeds.megaphone.fm/wethepeoplelive", 
    "http://feeds.wsjonline.com/wsj/podcast_wall_street_journal_tech_news_briefing", 
    "http://feeds.wsjonline.com/wsj/podcast_wall_street_journal_whats_news", 
    "http://feeds.wsjonline.com/wsj/podcast_your_money_matters", 
    "http://feeds.wsjonline.com/wsj/podcast_minute_briefing", 
    "https://feeds.megaphone.fm/parttimegenius", 
    "https://www.npr.org/rss/podcast.php?id=510307", 
    "https://feeds.megaphone.fm/thegrift", 
    "http://squanch.libsyn.com/rss", 
    "https://www.npr.org/rss/podcast.php?id=510308", 
    "https://www.npr.org/rss/podcast.php?id=510324", 
    "https://rss.art19.com/cults", 
    "https://www.npr.org/rss/podcast.php?id=510306", 
    "https://rss.art19.com/the-new-washington", 
    "https://www.npr.org/rss/podcast.php?id=510311", 
    "http://Feeds.gimletmedia.com/hearreplyall", 
    "http://postshowrecaps.com/feed/mr-robot/", 
    "http://feeds.lawson.media/moonshot/", 
    "http://melburno.org.au/3ZZZradio/feed/", 
    "http://thenewyorker.wm.wizzard.tv/rss", 
    "https://feeds.megaphone.fm/PPY8359579005", 
    "http://feeds.gimletmedia.com/sciencevs", 
    "http://feeds.megaphone.fm/veryfatalmurder", 
    "http://feeds.99percentinvisible.org/99percentinvisible", 
    "http://feeds.feedburner.com/skimmd", 
    "https://feeds.mozilla-podcasts.org/irl", 
    "https://rss.art19.com/late-night-with-seth-meyers-podcast", 
    "http://feeds.wnyc.org/trumpinc", 
    "https://www.relay.fm/playingforfun/feed", 
    "https://rss.art19.com/unexplained-mysteries", 
    "https://rss.art19.com/serial-killers", 
    "http://podcast.posttv.com/itunes-58861635e4b039a652877de6.xml", 
    "https://feeds.megaphone.fm/thehabitat", 
    "https://www.apatheticenthusiasm.com/feed/rickandmortypodcast/",
	"https://feeds.megaphone.fm/mupe"
];

// ,"http://feeds.gimletmedia.com/heavyweightpodcast"

export const defaultCasts = [
	{   "id": 0,
		"title": "The Daily",
		"description": "<p>This is what the news should sound like. The biggest stories of our time, told by the best journalists in the world. Hosted by Michael Barbaro. Twenty minutes a day, five days a week, ready by 6 a.m.</p>",
		"url": "https://art19.com/shows/the-daily",
		"image": "https://dfkfj8j276wwv.cloudfront.net/images/01/1b/f3/d6/011bf3d6-a448-4533-967b-e2f19e376480/7fdd4469c1b5cb3b66aa7dcc9fa21f138efe9a0310a8a269f3dcd07c83a552844fcc445ea2d53db1e55d6fb077aeaa8a1566851f8f2d8ac4349d9d23a87a69f5.jpeg",
		"domain": "rss.art19.com/the-daily"
	}, {
        "id": 1,
		"title": "Up First",
		"description": "NPR's <em>Up First</em> is the news you need to start your day. The biggest stories and ideas — from politics to pop culture — in 10 minutes. Hosted by Rachel Martin, David Greene and Steve Inskeep, with reporting and analysis from NPR News. Available weekdays by 6 a.m. ET. Subscribe and listen, then support your local NPR station at donate.npr.org.",
		"url": "http://www.npr.org/programs/morning-edition/",
		"image": "https://media.npr.org/assets/img/2017/03/21/upfirst_sq-ffcb53c89446b62b66fefb97b9356ad49b31bc5d.png?s=200",
		"domain": "www.npr.org/rss/podcast.php?id=510318"
	}
];
